#!/bin/bash 
#====================================================================
# NAME      :   bsp-probe
# AUTHOR    :   Andrys Jiri
# DATE      :   2019.03.08
VERSION='0.3'
#
# DEPENDENCIES :
#               bash, grep, awk, mkdir, find, sort, pwd, sha1sum,
#               bitbake-layers, git, printf, bitbake, cat, sed, mktemp
#               Any path must not include SPACES !
# 
#====================================================================

#have to be fullpath in both parameters
issubdir() {
    local _parentdir=$1
    local _subdir=$2
    #parentdir=/a/b/c
    #subdirdir=/a/b/c/d/e 
    _cutcommon=${_subdir/$_parentdir}
    
    if [ "${_cutcommon}" == "${_subdir}" ]; then
        #its not subdir ...unable to cut 
        return 1 
    else
        #is subdir -> ok
        #echo "  >Found" 
        return 0 
    fi
       
}

#1)existuje-layer-mimo-manifest-bez-git-repozitare??
#2)existuje-aktivni-layer--bez-git-repozitare ??
#does-layers-out-of-manifest-includes-git-folder ?

#return 0 if ok
#return !0 of not found
#custom is to not insert layer inside other layer ...only in this condition check is OK ! 
#TODO: This can be unreliable, reimplement later on ..check git and its objects ....

are-aktive-layers-part-of-git-dirs() {
    #check if active layers are included in git repositories if not -> error,
    # error -> manually added layers without .git must not be ever added 

    local _git_search_dir=$1
    local _logfle=$2
    
    echo -e "\n" >>"${_logfle}"
    
    echo -e "LAYERS-GIT-INCLUDE-CHECK:" >>"${_logfle}"
    
    _tmp=( $(find -L "${_git_search_dir}" -type d -path "*.git" | sort ) )
    #abs paths
    _git_dir_list=( ${_tmp[@]%*/.git} )
    #abs paths
    _active_layers_paths=$(bitbake-layers show-layers| awk 'FNR>2{print $2}' )

    for laydir in ${_active_layers_paths[@]}; do
        #is in git repo ? > no >error quit
        
        #echo "Laydir:$laydir" 
        found=0;
        for gitdir in ${_git_dir_list[@]}; do
        #found -> continue
            #echo "  >gitdir:$gitdir" 
            issubdir "${gitdir}"  "${laydir}"   
            if [ $? -eq 0 ]; then
                found=1;
                #one layer found in git 
                break;
            fi
        done
        
        if [ "${found}" -eq 0 ]; then
            #not found -> error
            echo -e ">ERROR: The ${laydir} is not part of any git repository."                                                     >>"${_logfle}"
            echo -e "        This may mean that BSP assembly includes external layers(out ouf manifest assembly) without .git ."    >>"${_logfle}"
            echo -e "        Nobody is able to identify final assembly."                                                           >>"${_logfle}"
            echo -e "        Please add yocto-layers together with .git "                                                          >>"${_logfle}"
            return 1;
        fi
        
    done

    #ok all layers are some part of git repository folder
    echo -e ">OK\n\n"                                                                                                              >>"${_logfle}"
    return 0;

}


get-local-config() {
    local _localconfiglog=$1

    #old bitbake/kernels should have this
    bwdir=$(bitbake virtual/kernel -e | grep ^BASE_WORKDIR=)
    bwdir="${bwdir#*=}"
    lconfig="${bwdir//\"}/../../conf/local.conf"

    if [ -e "${lconfig}" ]; then
        echo -e "\n\n{YOCTO_CONFIGURATION:[local.conf]" >>${_localconfiglog}
        cat "${lconfig}" >>${_localconfiglog}
        echo -e "}YOCTO_CONFIGURATION:[local.conf]\n" >>${_localconfiglog}
        echo -e "  >OK"
    else
        echo -e "\n    ERROR: Unable to find local.conf: -${lconfig}- . Exiting"
        return 1;
    fi
}



get-kernel-config() {
    local _kernelconfiglog=$1

    #old bitbake/kernels should have this
    wdir=$(bitbake virtual/kernel -e | grep ^WORKDIR=)
    wdir="${wdir#*=}"
    ykconfig="${wdir//\"}/build/.config"

    if [ -e "${ykconfig}" ]; then
        echo -e "\n\n{KERNEL_CONFIGURATION:[.config]" >>${_kernelconfiglog}
        cat "${ykconfig}" >>${_kernelconfiglog}
        echo -e "}KERNEL_CONFIGURATION:[.config]\n" >>${_kernelconfiglog}
        echo -e "  >OK"
    else
        echo -e "\n    ERROR: Unable to find kernel configuration: -${ykconfig}- . Exiting"
        return 1;
    fi

    #new bitbake/kernels should have this
    #stagkerdir=$(bitbake virtual/kernel -e | grep ^STAGING_KERNEL_BUILDDIR=)
#
#WORKDIR="/opt/xxxxx/works/fslbsp/build/tmp/work/imx8qxp_xxxx-poky-linux/linux-imx/4.9.51-r5"
#/build/.config
#or
#STAGING_KERNEL_BUILDDIR="/opt//works/fslbsp/build/tmp/work-shared/imx8qxp-xxxxx/kernel-build-artifacts"
#.config

}



file-hashes () {
    local _gitdatadir=$1
    local _base_searchpath=$2
    local _filehasheslog=$3

    #ignored_fls=( "/pyshtables.py" )
    
    git_links_list=( $(find -H "${_gitdatadir}" -type l -not -path "*/.git/*" ) )
    git_all_flist=( $(find -H "${_gitdatadir}" -type f -not -path "*/.git/*") ${git_links_list[@]} )
    git_all_slist=( $(printf '%s\n' ${git_all_flist[@]} | sort) )
    
    echo -e "  >${_gitdatadir}"
    echo -e "  {GIT_FILES_HASH:" >>"${_filehasheslog}"
    for fle in ${git_all_slist[@]}; do
    
        spath="${fle#"${_base_searchpath}/"}"
        [[ "${spath}" == *".pyc" ]] && continue
        [[ "${spath}" == *"/pyshtables.py" ]] && continue
    
        link=0
        for lnkfle in ${git_links_list[@]}; do 
            if [ "${fle}" == "${lnkfle}" ]; then
                link=1
                break;
            fi
        done
        
        if [ ${link} -eq 1 ]; then
            sha1=$(echo -n $(readlink "${fle}") | git hash-object --stdin)
        else
            sha1=$(git hash-object "${fle}")
        fi
 
        echo -e "${sha1}, ${spath}" >>"${_filehasheslog}"
        
        #fls_list_path+=( "${fle}" )
        #fls_list_sha1+=( "${sha1}" )
    done
    echo -e "}GIT_FILES_HASH" >>"${_filehasheslog}"

    echo -e "">>"${_filehasheslog}"

}



git-probe() {
    local _git_search_dir=$1
    local _logfle=$2
    local _get_branches=$3
    local _get_fullcheck=$4

    git_dir_list=( $(find -L "${_git_search_dir}" -type d -path "*.git" | sort ) )

    echo -e "\n" >>"${_logfle}"
    #TODO: fetched git does not include branches etc ..
    #      bellow mention method does not provide reliable result..

    if [ "${_get_branches}" == "yes" ]; then
        git config --global credential.helper 'cache --timeout 43200'
    fi

    if [ "${_get_fullcheck}" == "yes" ]; then
      echo -e "  GIT-FILES-HASH:"
    fi
    
    for gitdir in ${git_dir_list[@]}; do
        #tmp0="${gitdir%/*}"; tmp1=( ${tmp0//// } );tmp2=${tmp1[@]: -4};  tmp3=$(printf "%s/" ${tmp2[@]});
        #tmp0="${gitdir%/*}"; tmp1=( ${tmp0//// } );
        #gitrootdir=${tmp1[@]: -1};
        sgitdir="${gitdir%/*}";sgitdir="<LAYERS_DIR>/${gitdir//"${_git_search_dir}/"}"
        giturl=$(git --git-dir="${gitdir}" remote -v | awk 'NR==1{ print $2 }')
        commit_hash=$(git --git-dir="${gitdir}" show --format="%H" --no-patch)
        commit_date=$(git --git-dir="${gitdir}" show --format="%cI" --no-patch)
        tag_name=$(git --git-dir="${gitdir}" describe --tags --exact-match 2>/dev/null)
        on_base_of_tag=$(git --git-dir="${gitdir}" describe --tags --dirty 2>/dev/null)

        if [ "${_get_branches}" == "yes" ]; then
            _TMPDIR=$(mktemp -d)
            branch_name=$( cd ${_TMPDIR}; git clone ${giturl}; bla="${giturl##*/}"; cd "${bla%%.git*}" ; bla=$(git name-rev --name-only "${commit_hash}"); echo "${bla##*/}"  )
            # git name-rev --name-only
            printf '%s\n  %s\n  %s\n  %s\n  %s\n  %s\n\n' "GITDIR         :${sgitdir%/*}" "URL          :${giturl}" "Branch      :${branch_name}" "TAG          :${tag_name}" "HASH         :${commit_hash}" "DATE         :${commit_date}" >>"${_logfle}"
            rm -rf "${_TMPDIR}"
        else
            if [ "${_get_fullcheck}" == "yes" ]; then
                printf '%s\n  %s\n  %s\n  %s\n  %s\n  %s\n' "GITDIR       :${sgitdir%/*}" "URL        :${giturl}" "ON-BASE-OF :${on_base_of_tag}" "TAG        :${tag_name}"  "HASH       :${commit_hash}" "DATE       :${commit_date}" >>"${_logfle}"
            else
                printf '%s\n  %s\n  %s\n  %s\n  %s\n  %s\n\n' "GITDIR       :${sgitdir%/*}" "URL        :${giturl}" "ON-BASE-OF :${on_base_of_tag}" "TAG        :${tag_name}"  "HASH       :${commit_hash}" "DATE       :${commit_date}" >>"${_logfle}"
            fi
        fi

        if [ "${_get_fullcheck}" == "yes" ]; then
            file-hashes "${gitdir%/*}" "${_git_search_dir}" "${_logfle}"
        fi

    done

#reliable but slow:
#git clone --base URL
#cd "${giturl##*/}"
#git config --bool core.bare false
#mv "${giturl##*/}" .git
#git reset --hard
#it branch  --contains {HASH}

    echo -e "\n">>"${_logfle}"

}



repo-probe() {
    local _repo_git_dir=$1
    local _logfle=$2

    echo -e "\n" >>"${_logfle}"
    
    manfle="${_repo_git_dir%%"/manifests/.git"*}/manifest.xml"
    if [ ! -e "${manfle}" ]; then
        echo -e "ERROR: Unable to find manifest.xml ! Exiting"
        return 6;
    fi
    
    manname=$(readlink ${manfle})
    manname=${manname##*/}
    sha1sum=( $(sha1sum ${manfle}) )
    sha1sum=${sha1sum[0]}
    
    giturl=$(git --git-dir="${_repo_git_dir}" remote -v | awk 'NR==1{ print $2 }')
    commit_hash=$(git --git-dir="${_repo_git_dir}" show --format="%H" --no-patch)
    if [ ! $? -eq "0" ]; then
        echo -e "ERROR: Unable to get hash from git ! Exiting"
        return 7;
    fi    
    commit_date=$(git --git-dir="${_repo_git_dir}" show --format="%cI" --no-patch)
    tag_name=$(git --git-dir="${_repo_git_dir}" describe --tags --exact-match 2>/dev/null)

    printf '%s\n  %s\n  %s\n  %s\n  %s\n  %s\n' "MANIFEST-NAME :${manname}" "SHA1-SUM    :${sha1sum}" "URL         :${giturl}" "TAG         :${tag_name}" "COMIT-HASH  :${commit_hash}" "DATE        :${commit_date}" >>"${_logfle}"

    echo -e "  >OK"
    
}



dependencies_test() {
  #format: all commands here are in format "CMDNAME SOME_PARAMETERS RETURN_VALUE"

   for cmd in "${DEPENDENCIES_LIST[@]}"; do 
    #
    sub_cmd_arr=( ${cmd} )
    lst="${#sub_cmd_arr[@]}"
    sub_cmd="${sub_cmd_arr[@]:0:lst-1}"
    cmd_only=${sub_cmd_arr[0]}
    exp_retval="${sub_cmd_arr[@]: -1}"
    #
    
    retval=$( ${sub_cmd} &>/dev/null)
    retval=$?
    if [ "${retval}" != "${exp_retval}" ] && [ "${retval}" != "0" ]; then
      echo -e "  Error: Dependencies test fail !"
      echo -e '         "'$sub_cmd'" command should return 0 or "'$exp_retval'"'"\n         but returned value is "'"'$retval'"!' 
      return 1
    fi
   done

  return 0
}



help_desc() {
echo -e "\
  Usage:  bsp-probe OPTIONS

  Probe BSP on base of yocto project(OE, bitbake) and create bsp-probe.log
  The bsp-probe.log includes:
    - repo url, hash, tag, name of manifest.xml + hash
    - list of yocto layers
    - yocto layers revisions
    - git hashes of all source files 
    - local.conf
    - kernel configuration
  
  Command have to be executed in environment where bitbake command is available
  and
  after all layers have been added to bblayers.conf
  and
  configuration in local.conf for build is in final state 
  and
  build of image file have finished.

  OPTION: { --version }
  |  > Version information
  |

  OPTION: { --get-branches | -b }
  |  > Add info about branches. Unreliable results.
  |
"
}



#bitbake -s 0 ensure that we are in correct directory to get data from bitbake
DEPENDENCIES_LIST=( "grep --help 0" "awk BEGIN{print} 0" "mkdir --help 0" "git --version 0" "find --help 0" "bitbake -s 0" \
                    "sort --help 0" "pwd -L 0" "bitbake-layers --help 0"  "printf bla 0" "sed --help 0" "mktemp --help 0" "sha1sum --help 0")

main() {

    echo -e "\nBSP-PROBE:"

    GET_BRANCHES="no"
    FULL_CHECK="yes"
    
    for arg in "$@"; do

        case "$arg" in

          help|--help|-h|\?)
            help_desc
            exit 0;
          ;;

          --version)
            echo -e "Version: ${VERSION}"
            exit 0;
          ;;

          --get-branches|-b)
              GET_BRANCHES="yes"
          ;;

          --full-check|-f)
              FULL_CHECK="yes"
          ;;

        esac
    done

    
    
    CURWD=$(pwd)
    
    #Get-real bash script path: only one link level redirection
    if [ -L "$0" ]; then
        move2link=$(dirname "$0")
        resolv_link=$(readlink "$0")    
        BASHFILEDIR=$(cd "${move2link}"; cd -P $( dirname ${resolv_link} ) && pwd )
    else
        BASHFILEDIR=$(dirname "$0")
    fi
    
    echo -e "  DEPENDENCY-TEST:"
    dependencies_test
    ret=$?
    if [ "${ret}" != "0" ]; then  
      exit 1
    else
      echo -e "  >OK" 
    fi
    
    #TODO:Static path is enough, because of we are using mostly NXP based BSPs.This may not be functional in general for OE/Yocto BSPs. 
    SEARCH_ROOT_DIR="$(cd "${BASHFILEDIR}/../.."; pwd -P)"
    if [ ! $? -eq "0" ]; then 
        echo -e "\n  ERROR: Unable enter yocto layers directory ! Exiting \n"
        exit 2        
    fi
    
    #REPO_GIT_DIR
    if [ -e "${SEARCH_ROOT_DIR}/../.repo/manifests/.git" ]; then
        #nxp
        REPO_GIT_DIR="${SEARCH_ROOT_DIR}/../.repo/manifests/.git"
    elif [ -e "${SEARCH_ROOT_DIR}/.repo/manifest/.git" ]; then
       #agl and rest
        REPO_GIT_DIR="${SEARCH_ROOT_DIR}/.repo/manifests/.git"
    else
        echo -e "\n  ERROR: Unable to find .repo directory ! Exiting \n"
        exit 3
    fi
    
    #access check
    REPO_GIT_DIR="$(cd "${REPO_GIT_DIR}"; pwd -P)"
    if [ ! $? -eq "0" ]; then 
        echo -e "\n  ERROR: Unable enter .repo directory ! Exiting \n"
        exit 4        
    fi    
    
    
    BSP_PROBE_LOG="${CURWD}/bsp-probe.log"

    if [ "${BASHFILEDIR##*/}" != "tools" ]; then
      echo -e "\n  ERROR: Wrong script dir ! Exiting \n"
      exit 5
    fi

    if [ ! -e "${SEARCH_ROOT_DIR}/poky/bitbake" ]; then
        echo -e "\n  ERROR: Different BSP Structure:  SEARCH_ROOT_DIR:-${SEARCH_ROOT_DIR}- ! Exiting \n"
        exit 6
    fi

    CUR_TIME=$(date +%Y-%m-%d,%H:%M:%S)
    echo -e "BSP-PROBE[${CUR_TIME}]:" >"${BSP_PROBE_LOG}"
    echo -e "SEARCH_ROOT_DIR: ${SEARCH_ROOT_DIR}" >>"${BSP_PROBE_LOG}"
    echo -e "REPO_GIT_DIR: ${REPO_GIT_DIR%%"/manifests/.git"*}\n" >>"${BSP_PROBE_LOG}"
    
    
    echo -e "APPLIED LAYERS: ">>"${BSP_PROBE_LOG}"

    bitbake-layers show-layers | sed "s#${SEARCH_ROOT_DIR}/##g" >>"${BSP_PROBE_LOG}"
    ret_=$?
    if [ ! "${ret_}" -eq 0 ]; then
        echo -e "\n  ERROR: Command should be run from the same place as bitbake command ! Exiting \n"
        exit 7
    fi
    echo -e "\n" >>"${BSP_PROBE_LOG}"

    
    echo -e "  LAYERS-GIT-INCLUDE-CHECK:"
    are-aktive-layers-part-of-git-dirs "${SEARCH_ROOT_DIR}" "${BSP_PROBE_LOG}"
    ret_=$?
    if [ ! "${ret_}" -eq 0 ]; then    
        echo -e "  >ERROR: The ${laydir} is not part of any git repository."                                                   
        echo -e "          This may mean that BSP assembly includes external layers(out ouf manifest assembly) without .git ."    
        echo -e "          Nobody is able to identify final assembly."                                                 
        echo -e "          Please add yocto-layers together with .git"    
        echo -e "          Exiting"
        exit 8
    else
        echo -e "  >OK"
    fi
    
    echo -e "  REPO-PROBE:"
    repo-probe "${REPO_GIT_DIR}" "${BSP_PROBE_LOG}"

    git-probe "${SEARCH_ROOT_DIR}" "${BSP_PROBE_LOG}" "${GET_BRANCHES}" "${FULL_CHECK}"

    echo -e "  KERNEL-CONFIG:"
    get-kernel-config "${BSP_PROBE_LOG}"

    echo -e "  LOCAL-CONFIG:"
    get-local-config "${BSP_PROBE_LOG}"

    echo -e "\n"
}


main "$@"
